# Simulation experiment 

Run entire simulation experiment multiple times to generate confidence interval

In [1]:
%load_ext autoreload
%autoreload 2

from joblib import Parallel, delayed
import multiprocessing
import sys
import os
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

sys.path.append("../../")
from functions import pipelines

from numpy.random import seed
randomState = 123
seed(randomState)

Using TensorFlow backend.

In [2]:
# Parameters
dataset_name = "Human_analysis"
analysis_name = 'analysis_3'
NN_architecture = 'NN_2500_30'
file_prefix = 'Partition_corrected'
num_simulated_experiments = 50
lst_num_partitions = [1, 2, 3, 5, 10, 20,
                    30, 50]
corrected = True
use_pca = True
num_PCs = 10

iterations = range(5) 
num_cores = 5

In [3]:
# Input files
base_dir = os.path.abspath(
  os.path.join(
      os.getcwd(), "../.."))    # base dir on repo

normalized_data_file = os.path.join(
    base_dir,
    dataset_name,
    "data",
    "input",
    "recount2_gene_normalized_data.tsv.xz")

experiment_ids_file = os.path.join(
    base_dir,
    dataset_name,
    "data",
    "metadata",
    "recount2_experiment_ids.txt")

In [4]:
# Output files
similarity_corrected_file = os.path.join(
    base_dir,
    "results",
    "saved_variables",
    "analysis_3_similarity_corrected.pickle")

ci_corrected_file = os.path.join(
    base_dir,
    "results",
    "saved_variables",
    "analysis_3_ci_corrected.pickle")

In [5]:
# Run multiple simulations - corrected
results = Parallel(n_jobs=num_cores, verbose=100)(
    delayed(
        pipelines.matched_simulation_experiment_corrected)(i,
                                                           NN_architecture,
                                                           dataset_name,
                                                           analysis_name,
                                                           num_simulated_experiments,
                                                           lst_num_partitions,
                                                           corrected,
                                                           use_pca,
                                                           num_PCs,
                                                           file_prefix,
                                                           normalized_data_file,
                                                           experiment_ids_file) for i in iterations)

[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done   1 tasks      | elapsed: 126.6min
[Parallel(n_jobs=5)]: Done   2 out of   5 | elapsed: 126.8min remaining: 190.3min
[Parallel(n_jobs=5)]: Done   3 out of   5 | elapsed: 142.9min remaining: 95.3min
[Parallel(n_jobs=5)]: Done   5 out of   5 | elapsed: 193.0min remaining:    0.0s
[Parallel(n_jobs=5)]: Done   5 out of   5 | elapsed: 193.0min finished

In [6]:
# Concatenate output dataframes
all_svcca_scores = pd.DataFrame()

for i in iterations:
    all_svcca_scores = pd.concat([all_svcca_scores, results[i][1]], axis=1)

all_svcca_scores

                         score     score     score     score     score
number of partitions
1                     0.999983  0.999977  0.999980  0.999978  0.999986
2                     0.982884  0.976992  0.962698  0.980215  0.974150
3                     0.945332  0.961502  0.939444  0.956839  0.949975
5                     0.933063  0.931100  0.885549  0.923859  0.939430
10                    0.820516  0.857132  0.791742  0.808218  0.837881
20                    0.746280  0.708669  0.702383  0.723188  0.684485
30                    0.588178  0.627450  0.594722  0.607916  0.534393
50                    0.404348  0.380072  0.343686  0.380307  0.299579

In [7]:
# Get median for each row (number of experiments)
mean_scores = all_svcca_scores.mean(axis=1).to_frame()
mean_scores.columns = ['score']
mean_scores

                         score
number of partitions
1                     0.999981
2                     0.975388
3                     0.950618
5                     0.922600
10                    0.823098
20                    0.713001
30                    0.590532
50                    0.361598

In [8]:
# Get standard dev for each row (number of experiments)
import math
std_scores = (all_svcca_scores.std(axis=1)/math.sqrt(10)).to_frame()
std_scores.columns = ['score']
std_scores

                         score
number of partitions
1                     0.000001
2                     0.002473
3                     0.002786
5                     0.006781
10                    0.008044
20                    0.007342
30                    0.011000
50                    0.012929

In [9]:
# Get confidence interval for each row (number of experiments)
err = std_scores*1.96

In [10]:
# Get boundaries of confidence interval
ymax = mean_scores + err
ymin = mean_scores - err

ci = pd.concat([ymin, ymax], axis=1)
ci.columns = ['ymin', 'ymax']
ci

                          ymin      ymax
number of partitions
1                     0.999979  0.999983
2                     0.970541  0.980235
3                     0.945159  0.956078
5                     0.909309  0.935891
10                    0.807332  0.838864
20                    0.698611  0.727390
30                    0.568972  0.612092
50                    0.336258  0.386939

In [11]:
mean_scores

                         score
number of partitions
1                     0.999981
2                     0.975388
3                     0.950618
5                     0.922600
10                    0.823098
20                    0.713001
30                    0.590532
50                    0.361598

In [12]:
# Pickle dataframe of mean scores scores for first run, interval
mean_scores.to_pickle(similarity_corrected_file)
ci.to_pickle(ci_corrected_file)